package com.alastorkaneki.gitgui.git

data class GitCommandEntry(
    val name: String,
    val category: String,
    val description: String,
    val guiSupported: Boolean
)

object GitCommandCatalog {
    val entries = listOf(
        GitCommandEntry("add", "Working tree", "Stage file content for the next commit.", true),
        GitCommandEntry("am", "Patching", "Apply a mailbox of patches.", false),
        GitCommandEntry("apply", "Patching", "Apply a patch to files or the index.", false),
        GitCommandEntry("archive", "Export", "Create an archive from a tree.", false),
        GitCommandEntry("bisect", "History", "Find the commit that introduced a bug.", false),
        GitCommandEntry("blame", "Inspection", "Show the last change for each line.", false),
        GitCommandEntry("branch", "Branches", "List, create, rename, and delete branches.", true),
        GitCommandEntry("bundle", "Transfer", "Move repository data in a single file.", false),
        GitCommandEntry("cat-file", "Plumbing", "Inspect repository objects.", false),
        GitCommandEntry("check-attr", "Inspection", "Display gitattributes information.", false),
        GitCommandEntry("check-ignore", "Inspection", "Debug ignore rules.", false),
        GitCommandEntry("check-mailmap", "Inspection", "Resolve canonical contributor identities.", false),
        GitCommandEntry("check-ref-format", "References", "Validate reference names.", false),
        GitCommandEntry("checkout", "Working tree", "Switch branches or restore paths.", true),
        GitCommandEntry("cherry", "History", "Find commits not yet applied upstream.", false),
        GitCommandEntry("cherry-pick", "History", "Apply selected commits to the current branch.", true),
        GitCommandEntry("clean", "Working tree", "Remove untracked files and folders.", true),
        GitCommandEntry("clone", "Repository", "Clone a repository into app storage.", true),
        GitCommandEntry("column", "Formatting", "Format output into columns.", false),
        GitCommandEntry("commit", "History", "Record staged changes.", true),
        GitCommandEntry("commit-graph", "Maintenance", "Write and verify commit graph files.", false),
        GitCommandEntry("commit-tree", "Plumbing", "Create a commit object.", false),
        GitCommandEntry("config", "Configuration", "Read and write repository configuration.", false),
        GitCommandEntry("count-objects", "Maintenance", "Count unpacked objects and disk use.", false),
        GitCommandEntry("credential", "Authentication", "Read or write credential data.", false),
        GitCommandEntry("credential-cache", "Authentication", "Temporarily cache credentials.", false),
        GitCommandEntry("credential-store", "Authentication", "Store credentials on disk.", false),
        GitCommandEntry("describe", "History", "Name a commit relative to tags.", false),
        GitCommandEntry("diagnose", "Maintenance", "Collect repository diagnostics.", false),
        GitCommandEntry("diff", "Inspection", "Show differences between states.", true),
        GitCommandEntry("diff-files", "Plumbing", "Compare the working tree and index.", false),
        GitCommandEntry("diff-index", "Plumbing", "Compare a tree and the index.", false),
        GitCommandEntry("diff-tree", "Plumbing", "Compare tree objects.", false),
        GitCommandEntry("difftool", "Inspection", "Open differences in an external tool.", false),
        GitCommandEntry("fast-export", "Transfer", "Export repository history as a stream.", false),
        GitCommandEntry("fast-import", "Transfer", "Import repository history from a stream.", false),
        GitCommandEntry("fetch", "Remote", "Download refs and objects from a remote.", true),
        GitCommandEntry("fetch-pack", "Plumbing", "Receive missing objects from another repository.", false),
        GitCommandEntry("filter-branch", "History", "Rewrite branches using filters.", false),
        GitCommandEntry("for-each-ref", "References", "Format and inspect refs.", false),
        GitCommandEntry("format-patch", "Patching", "Prepare commits as email patches.", false),
        GitCommandEntry("fsck", "Maintenance", "Verify object connectivity and validity.", false),
        GitCommandEntry("fsmonitor--daemon", "Maintenance", "Track working tree changes.", false),
        GitCommandEntry("gc", "Maintenance", "Clean and optimize repository data.", false),
        GitCommandEntry("get-tar-commit-id", "Plumbing", "Read a commit ID from a Git archive.", false),
        GitCommandEntry("grep", "Inspection", "Search tracked content.", false),
        GitCommandEntry("hash-object", "Plumbing", "Compute and optionally write an object ID.", false),
        GitCommandEntry("help", "Help", "Open command documentation.", true),
        GitCommandEntry("index-pack", "Plumbing", "Build an index for a pack file.", false),
        GitCommandEntry("init", "Repository", "Create a new local repository.", true),
        GitCommandEntry("interpret-trailers", "Formatting", "Add or parse commit message trailers.", false),
        GitCommandEntry("log", "History", "Browse commit history.", true),
        GitCommandEntry("ls-files", "Inspection", "List files in the index and working tree.", true),
        GitCommandEntry("ls-remote", "Remote", "List references in a remote repository.", false),
        GitCommandEntry("ls-tree", "Plumbing", "List tree object contents.", false),
        GitCommandEntry("mailinfo", "Patching", "Extract patch and authorship data from email.", false),
        GitCommandEntry("mailsplit", "Patching", "Split an mbox into individual messages.", false),
        GitCommandEntry("maintenance", "Maintenance", "Run repository maintenance tasks.", false),
        GitCommandEntry("merge", "Branches", "Join histories together.", true),
        GitCommandEntry("merge-base", "History", "Find common ancestors.", false),
        GitCommandEntry("merge-file", "Patching", "Run a three-way file merge.", false),
        GitCommandEntry("merge-index", "Plumbing", "Run a merge helper on indexed files.", false),
        GitCommandEntry("merge-tree", "Plumbing", "Perform a merge without touching files.", false),
        GitCommandEntry("mergetool", "Working tree", "Resolve conflicts with a merge tool.", false),
        GitCommandEntry("mktag", "Plumbing", "Create a tag object with validation.", false),
        GitCommandEntry("mktree", "Plumbing", "Build a tree object from text input.", false),
        GitCommandEntry("multi-pack-index", "Maintenance", "Manage multi-pack indexes.", false),
        GitCommandEntry("mv", "Working tree", "Move or rename tracked files.", false),
        GitCommandEntry("name-rev", "History", "Find symbolic names for revisions.", false),
        GitCommandEntry("notes", "History", "Add or inspect notes attached to objects.", false),
        GitCommandEntry("pack-objects", "Plumbing", "Create packed object archives.", false),
        GitCommandEntry("pack-redundant", "Maintenance", "Find redundant pack files.", false),
        GitCommandEntry("pack-refs", "Maintenance", "Pack heads and tags efficiently.", false),
        GitCommandEntry("patch-id", "Patching", "Compute stable identifiers for patches.", false),
        GitCommandEntry("prune", "Maintenance", "Remove unreachable loose objects.", false),
        GitCommandEntry("prune-packed", "Maintenance", "Remove loose objects already packed.", false),
        GitCommandEntry("pull", "Remote", "Fetch and integrate remote changes.", true),
        GitCommandEntry("push", "Remote", "Upload commits and refs to a remote.", true),
        GitCommandEntry("range-diff", "Inspection", "Compare two commit ranges.", false),
        GitCommandEntry("read-tree", "Plumbing", "Read tree information into the index.", false),
        GitCommandEntry("rebase", "Branches", "Replay commits on a new base.", true),
        GitCommandEntry("reflog", "History", "Inspect changes to references.", false),
        GitCommandEntry("remote", "Remote", "Manage remote repositories.", true),
        GitCommandEntry("repack", "Maintenance", "Pack unpacked objects.", false),
        GitCommandEntry("replace", "References", "Create replacement object references.", false),
        GitCommandEntry("request-pull", "Remote", "Summarize changes for a pull request.", false),
        GitCommandEntry("rerere", "Conflicts", "Reuse recorded conflict resolutions.", false),
        GitCommandEntry("reset", "Working tree", "Reset HEAD, index, or files.", true),
        GitCommandEntry("restore", "Working tree", "Restore working tree files.", true),
        GitCommandEntry("rev-list", "Plumbing", "List reachable commit objects.", false),
        GitCommandEntry("rev-parse", "Plumbing", "Parse revision and repository information.", false),
        GitCommandEntry("revert", "History", "Create a commit that undoes another commit.", false),
        GitCommandEntry("rm", "Working tree", "Remove tracked files.", false),
        GitCommandEntry("send-email", "Patching", "Send patches by email.", false),
        GitCommandEntry("send-pack", "Plumbing", "Push objects over a Git protocol.", false),
        GitCommandEntry("shortlog", "History", "Summarize commits by author.", false),
        GitCommandEntry("show", "Inspection", "Show objects and commit details.", true),
        GitCommandEntry("show-branch", "Branches", "Compare branch histories.", false),
        GitCommandEntry("show-index", "Plumbing", "Inspect a pack index.", false),
        GitCommandEntry("show-ref", "References", "List local references.", false),
        GitCommandEntry("sparse-checkout", "Working tree", "Restrict the populated working tree.", false),
        GitCommandEntry("stage", "Working tree", "Alias for git add.", true),
        GitCommandEntry("stash", "Working tree", "Save and restore uncommitted changes.", true),
        GitCommandEntry("status", "Working tree", "Show working tree and index state.", true),
        GitCommandEntry("stripspace", "Formatting", "Remove unnecessary whitespace.", false),
        GitCommandEntry("submodule", "Repository", "Manage nested repositories.", false),
        GitCommandEntry("switch", "Branches", "Switch branches.", true),
        GitCommandEntry("symbolic-ref", "References", "Read or write symbolic refs.", false),
        GitCommandEntry("tag", "References", "Create, list, or delete tags.", true),
        GitCommandEntry("unpack-file", "Plumbing", "Create a temporary file from an object.", false),
        GitCommandEntry("unpack-objects", "Plumbing", "Unpack objects from a pack.", false),
        GitCommandEntry("update-index", "Plumbing", "Register file content in the index.", false),
        GitCommandEntry("update-ref", "References", "Safely update references.", false),
        GitCommandEntry("update-server-info", "Remote", "Refresh dumb HTTP transport metadata.", false),
        GitCommandEntry("upload-archive", "Plumbing", "Serve archive requests.", false),
        GitCommandEntry("upload-pack", "Plumbing", "Serve fetch and clone requests.", false),
        GitCommandEntry("var", "Configuration", "Display Git logical variables.", false),
        GitCommandEntry("verify-commit", "Inspection", "Verify commit signatures.", false),
        GitCommandEntry("verify-pack", "Maintenance", "Validate packed repository data.", false),
        GitCommandEntry("verify-tag", "Inspection", "Verify tag signatures.", false),
        GitCommandEntry("web--browse", "Help", "Open a URL in a browser.", false),
        GitCommandEntry("whatchanged", "History", "Show commits and raw diffs.", false),
        GitCommandEntry("worktree", "Repository", "Manage multiple working trees.", false),
        GitCommandEntry("write-tree", "Plumbing", "Create a tree from the index.", false)
    )
}
